# Generated by Django 3.1.4 on 2021-01-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_auto_20210106_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='description',
            field=models.CharField(default='no-description', max_length=30),
            preserve_default=False,
        ),
    ]
