# Generated by Django 3.1.4 on 2021-01-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0006_auto_20210108_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
