# Generated by Django 3.1.4 on 2021-01-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0009_auto_20210108_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='description',
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='results10',
            field=models.FileField(upload_to='results_files/'),
        ),
    ]
