# Generated by Django 3.1.4 on 2021-01-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0010_auto_20210109_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='benchmark',
        ),
        migrations.AddField(
            model_name='outcome',
            name='best',
            field=models.FloatField(default=-2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outcome',
            name='function',
            field=models.IntegerField(default=-2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outcome',
            name='mean',
            field=models.FloatField(default=-2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outcome',
            name='median',
            field=models.FloatField(default=-2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outcome',
            name='std',
            field=models.FloatField(default=-2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outcome',
            name='worst',
            field=models.FloatField(default=-2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Benchmark',
        ),
    ]
