# Generated by Django 3.1.4 on 2021-01-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0011_auto_20210109_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='counted',
            field=models.BooleanField(default=False),
        ),
    ]
