# Generated by Django 3.1.4 on 2021-01-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0013_auto_20210109_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='num_of_fun',
            field=models.IntegerField(default=0),
        ),
    ]
