# Generated by Django 3.1.4 on 2021-01-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0014_algorithm_num_of_fun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outcome',
            old_name='mean',
            new_name='mean_float',
        ),
        migrations.AddField(
            model_name='outcome',
            name='mean_str',
            field=models.CharField(default='no-value', max_length=30),
            preserve_default=False,
        ),
    ]
