# Generated by Django 3.1.4 on 2021-01-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0015_auto_20210110_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='SE',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
