# Generated by Django 3.1.4 on 2021-01-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0017_auto_20210110_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
