# Generated by Django 3.1.4 on 2021-01-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0021_auto_20210112_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='SR',
            field=models.IntegerField(default=0),
        ),
    ]
